const canvas=document.querySelector('#gameCanvas'),ctx=canvas.getContext('2d');
const ui={money:document.querySelector('#money'),lives:document.querySelector('#lives'),wave:document.querySelector('#wave'),start:document.querySelector('#startWave'),pause:document.querySelector('#pauseBtn'),toast:document.querySelector('#toast'),banner:document.querySelector('#waveBanner')};
const path=[[-30,160],[170,160],[245,225],[245,405],[425,405],[505,330],[720,330],[810,420],[1090,420]];
const specs={pen:{name:'Шариковая ручка',cost:35,range:118,rate:330,damage:13,color:'#4d78ca'},pencil:{name:'Карандаш',cost:50,range:175,rate:680,damage:31,color:'#e4a633'},eraser:{name:'Ластик',cost:40,range:105,rate:880,damage:8,color:'#e67d88',slow:0.56}};
let money=80,lives=20,wave=1,selected='pen',running=false,paused=false,enemies=[],towers=[],shots=[],last=0,spawned=0,spawnTimer=0;
function toast(t){ui.toast.textContent=t;ui.toast.classList.add('show');setTimeout(()=>ui.toast.classList.remove('show'),1600)}
document.querySelectorAll('.tower').forEach(b=>b.onclick=()=>{selected=b.dataset.tower;document.querySelectorAll('.tower').forEach(x=>x.classList.toggle('active',x===b));toast('Выбрано: '+specs[selected].name)});
ui.pause.onclick=()=>{paused=!paused;ui.pause.textContent=paused?'▶':'Ⅱ';toast(paused?'Урок на паузе':'Продолжаем урок!')};
ui.start.onclick=()=>{if(running)return;running=true;spawned=0;spawnTimer=0;ui.start.style.display='none';ui.banner.innerHTML=`<span>ВОЛНА ${wave}</span><b>УЧЕБНИКИ В АТАКЕ!</b>`;toast('Волна началась!')};
canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;if(distanceToPath(x,y)<46){toast('Нельзя ставить на дорожке!');return}if(towers.some(t=>Math.hypot(t.x-x,t.y-y)<55)){toast('Слишком близко к другой башне');return}let s=specs[selected];if(money<s.cost){toast('Не хватает канцелярии');return}money-=s.cost;towers.push({x,y,type:selected,cool:0,angle:-1.57});sync();toast(s.name+' готова к уроку!')};
function distanceToPath(x,y){let m=1e9;for(let i=0;i<path.length-1;i++){let[a,b]=[path[i],path[i+1]],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy)));m=Math.min(m,Math.hypot(x-(a[0]+t*dx),y-(a[1]+t*dy)))}return m}
function enemy(){return{x:-20,y:160,seg:0,progress:0,hp:wave===5?115:48+wave*12,max:wave===5?115:48+wave*12,speed:42+wave*5,slow:0,dead:false}}
function sync(){ui.money.textContent=money;ui.lives.textContent=lives;ui.wave.textContent=`${wave} / 5`}
function update(dt){if(paused)return;if(running){spawnTimer-=dt;let count=4+wave*2;if(spawned<count&&spawnTimer<=0){enemies.push(enemy());spawned++;spawnTimer=650}if(spawned===count&&!enemies.length){running=false;if(wave===5){ui.start.style.display='block';ui.start.textContent='★ ПОБЕДА!';ui.start.disabled=true;ui.banner.innerHTML='<span>ОТЛИЧНАЯ РАБОТА</span><b>КЛАСС СПАСЁН!</b>';toast('Пять с плюсом!')}else{wave++;money+=35;sync();ui.start.style.display='block';ui.start.textContent='▶ НАЧАТЬ ВОЛНУ';ui.banner.innerHTML=`<span>ВОЛНА ${wave}</span><b>ПОДГОТОВКА К УРОКУ</b>`;toast('Волна пройдена! +35 ✦')}}}
enemies.forEach(en=>{let sp=en.speed*(en.slow>0?.56:1)*dt/1000;en.slow=Math.max(0,en.slow-dt);while(sp>0&&en.seg<path.length-1){let a=path[en.seg],b=path[en.seg+1],len=Math.hypot(b[0]-a[0],b[1]-a[1]),rem=len-en.progress;if(sp<rem){en.progress+=sp;sp=0}else{sp-=rem;en.seg++;en.progress=0}}if(en.seg>=path.length-1){en.dead=true;lives--;sync();if(lives<=0){running=false;toast('Звонок прозвенел... Попробуйте снова');ui.start.style.display='block';ui.start.textContent='↻ НАЧАТЬ СНАЧАЛА'}}let a=path[Math.min(en.seg,path.length-2)],b=path[Math.min(en.seg+1,path.length-1)],len=Math.hypot(b[0]-a[0],b[1]-a[1]);en.x=a[0]+(b[0]-a[0])*en.progress/len;en.y=a[1]+(b[1]-a[1])*en.progress/len});
towers.forEach(t=>{t.cool-=dt;let s=specs[t.type],target=enemies.filter(e=>!e.dead&&Math.hypot(e.x-t.x,e.y-t.y)<s.range).sort((a,b)=>b.seg-a.seg)[0];if(target){t.angle=Math.atan2(target.y-t.y,target.x-t.x);if(t.cool<=0){target.hp-=s.damage;if(s.slow)target.slow=900;shots.push({x:t.x,y:t.y,tx:target.x,ty:target.y,color:s.color,life:130});t.cool=s.rate;if(target.hp<=0){target.dead=true;money+=9;sync()}}}});shots.forEach(s=>s.life-=dt);enemies=enemies.filter(e=>!e.dead);shots=shots.filter(s=>s.life>0)}
function draw(){ctx.clearRect(0,0,1060,600);ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(...path[0]);path.slice(1).forEach(p=>ctx.lineTo(...p));ctx.strokeStyle='#e2c77c';ctx.lineWidth=47;ctx.stroke();ctx.strokeStyle='#fff6d7';ctx.lineWidth=38;ctx.stroke();ctx.setLineDash([3,9]);ctx.strokeStyle='#e2d095';ctx.lineWidth=2;ctx.stroke();ctx.setLineDash([]);path.slice(1,-1).forEach((p,i)=>{ctx.fillStyle='#f6a45d';ctx.beginPath();ctx.arc(p[0],p[1],5,0,7);ctx.fill()});towers.forEach(t=>drawTower(t));enemies.forEach(drawBook);shots.forEach(s=>{ctx.strokeStyle=s.color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.tx,s.ty);ctx.stroke()});}
function drawTower(t){let s=specs[t.type];ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,0,22,0,7);ctx.fill();ctx.strokeStyle='#d6dfef';ctx.lineWidth=2;ctx.stroke();ctx.rotate(t.angle);ctx.strokeStyle=s.color;ctx.lineWidth=t.type==='pencil'?8:7;ctx.beginPath();ctx.moveTo(-4,0);ctx.lineTo(22,0);ctx.stroke();if(t.type==='eraser'){ctx.fillStyle=s.color;ctx.fillRect(-10,-10,19,20)}else{ctx.fillStyle=s.color;ctx.beginPath();ctx.arc(-3,0,9,0,7);ctx.fill()}ctx.restore()}
function drawBook(e){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(.08);ctx.fillStyle='#fd8e81';ctx.fillRect(-14,-19,28,38);ctx.fillStyle='#ffb6a9';ctx.fillRect(-10,-15,19,30);ctx.fillStyle='#fff3da';ctx.fillRect(4,-15,5,30);ctx.fillStyle='#24345d';ctx.beginPath();ctx.arc(-5,-2,2,0,7);ctx.arc(4,-2,2,0,7);ctx.fill();ctx.strokeStyle='#24345d';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,5,4,0,3.14);ctx.stroke();ctx.restore();ctx.fillStyle='#fff';ctx.fillRect(e.x-17,e.y-28,34,4);ctx.fillStyle='#75c7a7';ctx.fillRect(e.x-17,e.y-28,34*e.hp/e.max,4)}
function frame(now){let dt=Math.min(40,now-last||16);last=now;update(dt);draw();requestAnimationFrame(frame)}sync();requestAnimationFrame(frame);
