const c=document.querySelector('#gameCanvas'),x=c.getContext('2d'),P=[[-30,160],[170,160],[245,225],[245,405],[425,405],[505,330],[720,330],[810,420],[1090,420]],S={pen:['Ручка',35,118,13,'#4d78ca'],pencil:['Карандаш',50,175,31,'#e4a633'],eraser:['Ластик',40,105,8,'#e67d88']};let gold=80,life=20,wave=1,sel='pen',run=0,spawn=0,es=[],ts=[],chosen,mouse={x:-1,y:-1};const $=id=>document.querySelector(id),sync=()=>{$('#money').textContent=gold;$('#lives').textContent=life;$('#wave').textContent=wave+' / 5';card()},stat=t=>({r:S[t.k][2]+(t.l-1)*12,d:S[t.k][3]+(t.l-1)*7}),note=s=>{$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1400)};
function card(){let q=$('#upgradeCard');q.hidden=!chosen;if(!chosen)return;let z=chosen.l==5;$('#upgradeTitle').textContent=S[chosen.k][0];$('#towerLevel').textContent=chosen.l+' / 5';$('#upgradeCost').textContent=z?'МАКС.':(25+chosen.l*25)+' ✦';$('#upgradeBtn').disabled=z||gold<25+chosen.l*25;$('#abilityBtn').disabled=!z||Date.now()<chosen.cd;$('#abilityBtn').textContent=!z?'СПОСОБНОСТЬ ОТКРОЕТСЯ НА 5 УР.':Date.now()<chosen.cd?'ПЕРЕЗАРЯДКА':'АКТИВИРОВАТЬ: '+({pen:'КРАСНАЯ ПАСТА',pencil:'ТРОЙНОЙ ВЫСТРЕЛ',eraser:'СТАН ВСЕХ'})[chosen.k];$('#upgradeHint').textContent=z?'Способность готова!':'Урон и радиус растут на каждом уровне.'}
$('.tower').onclick=()=>{};document.querySelectorAll('.tower').forEach(b=>b.onclick=()=>{sel=b.dataset.tower;document.querySelectorAll('.tower').forEach(z=>z.classList.toggle('active',z==b))});
$('#upgradeBtn').onclick=()=>{let n=25+chosen.l*25;if(gold>=n&&chosen.l<5){gold-=n;chosen.l++;sync();note('Уровень повышен!')}};$('#abilityBtn').onclick=()=>{let t=chosen;if(!t||Date.now()<t.cd)return;t.cd=Date.now()+({pen:16000,pencil:18000,eraser:25000})[t.k];if(t.k==='pen'){let e=es.find(e=>Math.hypot(e.x-t.x,e.y-t.y)<stat(t).r);if(e)e.mark=10000;note('Красная метка на 10 сек.')}if(t.k==='pencil'){t.triple=5000;note('Тройной выстрел на 5 сек.')}if(t.k==='eraser'){es.forEach(e=>e.stun=3000);note('Все учебники в стане 3 сек.')}card()};
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}c.onmousemove=e=>{let r=c.getBoundingClientRect();mouse={x:(e.clientX-r.left)*1060/r.width,y:(e.clientY-r.top)*600/r.height}};c.onclick=e=>{let r=c.getBoundingClientRect(),p={x:(e.clientX-r.left)*1060/r.width,y:(e.clientY-r.top)*600/r.height},hit=ts.find(t=>dist(t,p)<30);if(hit){chosen=hit;sync();return}if(gold<S[sel][1])return note('Не хватает канцелярии');gold-=S[sel][1];ts.push({x:p.x,y:p.y,k:sel,l:1,cd:0,triple:0});sync()};
$('#startWave').onclick=()=>{if(run)return;run=1;spawn=0;$('#startWave').style.display='none'};function add(){let type=wave==5&&spawn==9?'boss':spawn%5==3?'tank':spawn%5==4?'fast':'normal',a={normal:[1,1,'#fd8e81'],tank:[3.3,.5,'#7768af'],fast:[.48,2,'#5bb9a6'],boss:[13,.6,'#d65c6b']}[type],hp=(50+wave*12)*a[0];es.push({x:-20,y:160,i:0,p:0,h:hp,m:hp,v:(45+wave*5)*a[1],type,col:a[2],mark:0,stun:0})}let tick=0;
function upd(d){if(run&&(tick-=d)<0&&spawn<(wave==5?10:8)){add();spawn++;tick=650}es.forEach(e=>{e.mark-=d;e.stun-=d;if(e.stun>0)return;let z=e.v*d/1000,a=P[e.i],b=P[e.i+1],l=Math.hypot(b[0]-a[0],b[1]-a[1]);e.p+=z;if(e.p>=l){e.p=0;e.i++;if(e.i==P.length-1){e.dead=1;life--}}a=P[Math.min(e.i,P.length-2)];b=P[Math.min(e.i+1,P.length-1)];l=Math.hypot(b[0]-a[0],b[1]-a[1]);e.x=a[0]+(b[0]-a[0])*e.p/l;e.y=a[1]+(b[1]-a[1])*e.p/l});ts.forEach(t=>{t.triple-=d;let e=es.find(e=>dist(t,e)<stat(t).r);if(e&&(t.cool=(t.cool||0)-d)<0){let hit=q=>{q.h-=stat(t).d+(q.mark>0?12:0);if(q.h<=0){q.dead=1;gold+=q.type==='boss'?100:10}};hit(e);if(t.triple>0)es.filter(q=>q!=e&&dist(t,q)<stat(t).r).slice(0,2).forEach(hit);t.cool=420}});es=es.filter(e=>!e.dead);if(run&&spawn>=(wave==5?10:8)&&!es.length){run=0;if(wave++<5){gold+=35;$('#startWave').style.display='block'}else note('Победа!')}sync()}
function draw(){x.clearRect(0,0,1060,600);x.beginPath();x.moveTo(...P[0]);P.slice(1).forEach(p=>x.lineTo(...p));x.lineWidth=40;x.strokeStyle='#fff2c7';x.stroke();let h=ts.find(t=>dist(t,mouse)<30)||chosen;if(h){x.beginPath();x.arc(h.x,h.y,stat(h).r,0,7);x.fillStyle=S[h.k][4]+'22';x.fill();x.strokeStyle=S[h.k][4];x.setLineDash([5,5]);x.stroke();x.setLineDash([])}ts.forEach(t=>{x.fillStyle=S[t.k][4];x.beginPath();x.arc(t.x,t.y,18,0,7);x.fill();x.fillStyle='#fff';x.font='bold 11px Arial';x.fillText(t.l,t.x-3,t.y+4)});es.forEach(e=>{x.fillStyle=e.mark>0?'#e43d49':e.col;x.fillRect(e.x-13,e.y-18,e.type==='boss'?38:26,e.type==='boss'?50:36);x.fillStyle='#fff';x.fillRect(e.x-16,e.y-27,35,4);x.fillStyle='#65bd99';x.fillRect(e.x-16,e.y-27,35*e.h/e.m,4);if(e.stun>0){x.fillStyle='#315da5';x.fillText('✦',e.x,e.y-35)}})}let last=0;function f(n){let d=Math.min(40,n-last||16);last=n;upd(d);draw();requestAnimationFrame(f)}sync();requestAnimationFrame(f);
const canvas=document.querySelector('#gameCanvas'),ctx=canvas.getContext('2d');
const ui={money:document.querySelector('#money'),lives:document.querySelector('#lives'),wave:document.querySelector('#wave'),start:document.querySelector('#startWave'),pause:document.querySelector('#pauseBtn'),toast:document.querySelector('#toast'),banner:document.querySelector('#waveBanner')};
const path=[[-30,160],[170,160],[245,225],[245,405],[425,405],[505,330],[720,330],[810,420],[1090,420]];
const specs={pen:{name:'Шариковая ручка',cost:35,range:118,rate:330,damage:13,color:'#4d78ca'},pencil:{name:'Карандаш',cost:50,range:175,rate:680,damage:31,color:'#e4a633'},eraser:{name:'Ластик',cost:40,range:105,rate:880,damage:8,color:'#e67d88',slow:0.56}};
let money=80,lives=20,wave=1,selected='pen',running=false,paused=false,enemies=[],towers=[],shots=[],last=0,spawned=0,spawnTimer=0;
function toast(t){ui.toast.textContent=t;ui.toast.classList.add('show');setTimeout(()=>ui.toast.classList.remove('show'),1600)}
document.querySelectorAll('.tower').forEach(b=>b.onclick=()=>{selected=b.dataset.tower;document.querySelectorAll('.tower').forEach(x=>x.classList.toggle('active',x===b));toast('Выбрано: '+specs[selected].name)});
ui.pause.onclick=()=>{paused=!paused;ui.pause.textContent=paused?'▶':'Ⅱ';toast(paused?'Урок на паузе':'Продолжаем урок!')};
ui.start.onclick=()=>{if(running)return;running=true;spawned=0;spawnTimer=0;ui.start.style.display='none';ui.banner.innerHTML=`<span>ВОЛНА ${wave}</span><b>УЧЕБНИКИ В АТАКЕ!</b>`;toast('Волна началась!')};
canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;if(distanceToPath(x,y)<46){toast('Нельзя ставить на дорожке!');return}if(towers.some(t=>Math.hypot(t.x-x,t.y-y)<55)){toast('Слишком близко к другой башне');return}let s=specs[selected];if(money<s.cost){toast('Не хватает канцелярии');return}money-=s.cost;towers.push({x,y,type:selected,cool:0,angle:-1.57});sync();toast(s.name+' готова к уроку!')};
function distanceToPath(x,y){let m=1e9;for(let i=0;i<path.length-1;i++){let[a,b]=[path[i],path[i+1]],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy)));m=Math.min(m,Math.hypot(x-(a[0]+t*dx),y-(a[1]+t*dy)))}return m}
function enemy(){return{x:-20,y:160,seg:0,progress:0,hp:wave===5?115:48+wave*12,max:wave===5?115:48+wave*12,speed:42+wave*5,slow:0,dead:false}}
function sync(){ui.money.textContent=money;ui.lives.textContent=lives;ui.wave.textContent=`${wave} / 5`}
function update(dt){if(paused)return;if(running){spawnTimer-=dt;let count=4+wave*2;if(spawned<count&&spawnTimer<=0){enemies.push(enemy());spawned++;spawnTimer=650}if(spawned===count&&!enemies.length){running=false;if(wave===5){ui.start.style.display='block';ui.start.textContent='★ ПОБЕДА!';ui.start.disabled=true;ui.banner.innerHTML='<span>ОТЛИЧНАЯ РАБОТА</span><b>КЛАСС СПАСЁН!</b>';toast('Пять с плюсом!')}else{wave++;money+=35;sync();ui.start.style.display='block';ui.start.textContent='▶ НАЧАТЬ ВОЛНУ';ui.banner.innerHTML=`<span>ВОЛНА ${wave}</span><b>ПОДГОТОВКА К УРОКУ</b>`;toast('Волна пройдена! +35 ✦')}}}
enemies.forEach(en=>{let sp=en.speed*(en.slow>0?.56:1)*dt/1000;en.slow=Math.max(0,en.slow-dt);while(sp>0&&en.seg<path.length-1){let a=path[en.seg],b=path[en.seg+1],len=Math.hypot(b[0]-a[0],b[1]-a[1]),rem=len-en.progress;if(sp<rem){en.progress+=sp;sp=0}else{sp-=rem;en.seg++;en.progress=0}}if(en.seg>=path.length-1){en.dead=true;lives--;sync();if(lives<=0){running=false;toast('Звонок прозвенел... Попробуйте снова');ui.start.style.display='block';ui.start.textContent='↻ НАЧАТЬ СНАЧАЛА'}}let a=path[Math.min(en.seg,path.length-2)],b=path[Math.min(en.seg+1,path.length-1)],len=Math.hypot(b[0]-a[0],b[1]-a[1]);en.x=a[0]+(b[0]-a[0])*en.progress/len;en.y=a[1]+(b[1]-a[1])*en.progress/len});
towers.forEach(t=>{t.cool-=dt;let s=specs[t.type],target=enemies.filter(e=>!e.dead&&Math.hypot(e.x-t.x,e.y-t.y)<s.range).sort((a,b)=>b.seg-a.seg)[0];if(target){t.angle=Math.atan2(target.y-t.y,target.x-t.x);if(t.cool<=0){target.hp-=s.damage;if(s.slow)target.slow=900;shots.push({x:t.x,y:t.y,tx:target.x,ty:target.y,color:s.color,life:130});t.cool=s.rate;if(target.hp<=0){target.dead=true;money+=9;sync()}}}});shots.forEach(s=>s.life-=dt);enemies=enemies.filter(e=>!e.dead);shots=shots.filter(s=>s.life>0)}
function draw(){ctx.clearRect(0,0,1060,600);ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(...path[0]);path.slice(1).forEach(p=>ctx.lineTo(...p));ctx.strokeStyle='#e2c77c';ctx.lineWidth=47;ctx.stroke();ctx.strokeStyle='#fff6d7';ctx.lineWidth=38;ctx.stroke();ctx.setLineDash([3,9]);ctx.strokeStyle='#e2d095';ctx.lineWidth=2;ctx.stroke();ctx.setLineDash([]);path.slice(1,-1).forEach((p,i)=>{ctx.fillStyle='#f6a45d';ctx.beginPath();ctx.arc(p[0],p[1],5,0,7);ctx.fill()});towers.forEach(t=>drawTower(t));enemies.forEach(drawBook);shots.forEach(s=>{ctx.strokeStyle=s.color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.tx,s.ty);ctx.stroke()});}
function drawTower(t){let s=specs[t.type];ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,0,22,0,7);ctx.fill();ctx.strokeStyle='#d6dfef';ctx.lineWidth=2;ctx.stroke();ctx.rotate(t.angle);ctx.strokeStyle=s.color;ctx.lineWidth=t.type==='pencil'?8:7;ctx.beginPath();ctx.moveTo(-4,0);ctx.lineTo(22,0);ctx.stroke();if(t.type==='eraser'){ctx.fillStyle=s.color;ctx.fillRect(-10,-10,19,20)}else{ctx.fillStyle=s.color;ctx.beginPath();ctx.arc(-3,0,9,0,7);ctx.fill()}ctx.restore()}
function drawBook(e){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(.08);ctx.fillStyle='#fd8e81';ctx.fillRect(-14,-19,28,38);ctx.fillStyle='#ffb6a9';ctx.fillRect(-10,-15,19,30);ctx.fillStyle='#fff3da';ctx.fillRect(4,-15,5,30);ctx.fillStyle='#24345d';ctx.beginPath();ctx.arc(-5,-2,2,0,7);ctx.arc(4,-2,2,0,7);ctx.fill();ctx.strokeStyle='#24345d';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,5,4,0,3.14);ctx.stroke();ctx.restore();ctx.fillStyle='#fff';ctx.fillRect(e.x-17,e.y-28,34,4);ctx.fillStyle='#75c7a7';ctx.fillRect(e.x-17,e.y-28,34*e.hp/e.max,4)}
function frame(now){let dt=Math.min(40,now-last||16);last=now;update(dt);draw();requestAnimationFrame(frame)}sync();requestAnimationFrame(frame);
